### ISSUE TITLE
How to use reportportal with out Docker

### ISSUE THREAD

**Issue by Bharadwaj-vana** [reportportal/shell-installation#2]
HI Team,

I am  looking for a solution to use report portal in one of my projects where we don't want to use any Docker. In this case how can I config report portal in to my TestNG framework to validate / analyze TestNG reports and display on dashboard. 

Can you please explain me in detail with steps would be great as I am new to this. 

Thanks In Advance

Thanks,
Bharadwaj

**Comment by HardNorth** [comment]
You have all instructions for non-docker installation in this repository, everything else is absolutely the same as for docker deployment. You can refer our examples: https://github.com/reportportal/examples-java
